% Two main directories for data, and scripts of this nature
% to provide the interface - 
%   data - where the federated databases are kept
%   acquisition - where raw data files generated by symphony are kept

% Enter appropriate names and owner and password to create
% delete when done, then use 'NewDataContext' to connect

newDatabaseName = 'database1'
owner = 'tony'
password = 'SuksiVittu'

acquisitionFolder = sprintf('/Users/%s/acquisition',owner);
dataFolder = sprintf('/Users/%s/data',owner);
connection_file = fullfile(dataFolder, sprintf('%s.connection',newDatabaseName));

%% Delete the local sandox database
ovation.util.deleteLocalOvationDatabase(connection_file);


%% Build a new local sandbox database in data/
% State the name of the new database

connection_file = ovation.util.createLocalOvationDatabase(dataFolder, ...
    newDatabaseName,...
    owner,...
    password...
    );
import ovation.*;
context = Ovation.connect(connection_file, owner, password);

%% Open a context if the above is already run

context = NewDataContext(connection_file, 'tony');
contextViewer

%% Open a new project, or use one that exists

import org.joda.*;
project_name = 'Adaptive Dynamics of Signal Processing in the Mammalian Retina: Implications to Optimal Strategies of Neural Computations';
purpose = 'Understand nonlinear processing at visual threshold';

project = context.insertProject(project_name, 'To learn about Parkinsons through mice', datetime());
project.addTag('funded Academy of Finland');
contextViewer

%%
expName = 'Example experiment of LED traces';

year = 2012;
month = 9;
day = 26;

%experiment = project.getExperiments(datetime(year,month,day));
experiment = project.insertExperiment('Example experiment of LED traces', datetime(year,month,day));
% TODO: can we remove experiments?

experiment = experiment(1) %#ok<NOPTS>
contextViewer

%% insert experiment symphony data into an experiment

h5File = '091412Ac3.h5'
xmlFile = '091412Ac3_metadata.xml'

h5Path = fullfile(acquisitionFolder,h5File);
xmlPath = fullfile(acquisitionFolder,xmlFile);

epochGroups = SymphonyImport(context, h5Path, xmlPath,experiment);


