%% Importing new epoch
% need source

D = 'C:\Users\Anthony Azevedo\Raw_Data';
celldir = '131126';
celldirs = dir([fullfile(D,celldir) '\' celldir '*']);

%for celld = 1:length(celldirs)
    dv = datevec(celldirs(celld).date)
    % create Source
    % create Expeiemrnt
    cellSource = context.getObjectWithURI('ovation://9dc60a32-65bc-4ff5-8df5-70acc8e73761/');
    experiment = context.getObjectWithURI('ovation://6607282e-7953-42e8-bd70-00074a6aaa55/');
    cellGroup = experiment.insertEpochGroup(celldirs(celld).name,...
                                        datetime(dv(1),dv(2),dv(3),dv(4),dv(5),dv(6)),...
                                        [],... 
                                        [],...
                                        []);
    importCellBlocks(fullfile(D,celldir),celldirs(celld),cellGroup,cellSource)                              
%end

bigSpiker = context.getObjectWithURI('ovation://2fd19a3f-91a1-4cd1-8e59-6aac67fdf9da/');
        
% need experiment
experiment = context.getObjectWithURI('ovation://e930155d-db71-4487-a862-48555be36ec6/');

% need protocol
currentSineProtocol = context.getProtocol('CurrentSine');
if(isempty(currentSineProtocol))
    currentSineProtocol = context.insertProtocol('CurrentSine', 'Inject current sine wave',...
        'CurrentSine',...
        'https://github.com/tony-azevedo/FlySound/',...
        'e5f0b4bc7fa1445f41e19d60f6a3f92dd04d455f');
end

% find all the blocks
% for all blocks
b = dir(regexprep(Trial.name,'Acquisition','Raw_Data'));
epochGroup = experiment.insertEpochGroup(currentSineProtocol.getName,...
                                        datevec(b.date),...
                                        currentSineProtocol,... 
                                        piezoSineProtocolParams,...
                                        piezoSineDeviceParams);



%% Create an epoch group to contain the PiezoSine epochs
% I made the choice to attach the PiezoSine protocol here (instead of at 
% the Experiment). For data generated by a different protocol during this 
% Experiment (PiezoStep, Sweep, etc), I imagine you'd create a new sibling
% epochGroup, with a new protocol.

piezoSineProtocolParams = struct2map(params);
piezoSineDeviceParams = struct2map(equipmentSetupStruct);

epochGroup = experiment.insertEpochGroup('PiezoSine',...
                                        datetime(2013,7,1,8),...
                                        currentSineProtocol,... 
                                        piezoSineProtocolParams,...
                                        piezoSineDeviceParams);

% Then, when you insert epochs, you don't need to specify a protocol

epochProtocolParams.amplitude = 1;
piezoSineEpoch = epochGroup.insertEpoch(...					
					start,... 
                    fin,... 
					currentSineProtocol,...
                    struct2map(epochProtocolParams),...
                    piezoSineDeviceParams);

%% Adding Numeric data
% Device names are optional, and should correlate with keys in the
% EquipmentSetup map

deviceNames = array2set(['PiezoActuator']);
sourceNames = array2set(['F1']);
numericData = NumericData();
numericData.addData('sgsmonitor', sgsmonitor', 'V', params.sampratein, 'Hz');
piezoSineEpoch.insertNumericMeasurement(name,...
                                        sourceNames,...
                                        deviceNames,...
                                        numericData);
                                    
numericData = NumericData();
numericData.addData('voltage', voltage', 'mV',  params.sampratein, 'Hz');
piezoSineEpoch.insertNumericMeasurement(name,...
                                        sourceNames,...
                                        deviceNames,...
                                        numericData);
 
% TA: Where should I put the genotype of the fly (Source - child of fly?)?
% TA: what should the device names be ("Piezo Actuator" or more specific "Physik Instrumente P840.20"?
% TA: what are typical device params like?
% TA: woah!  This didn't work!  cause a bunch of errors
